#!/bin/sh
jsac -v -o AllTestsNS.web AllTestsNS.html \
	../JsUnit.js ../JsUnitNSServer.js ../CallStack.js \
	ArrayTest.js \
	money/AbstractFunctionCalledException.js money/IMoney.js \
	money/Money.js money/MoneyBag.js money/MoneyTest.js \
	SimpleTest.js

