<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!--
JsUnit - a JUnit port for JavaScript
Copyright (C) 1999,2000,2001,2002,2003 Joerg Schaible

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation in version 2 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

Test suites built with JsUnit are derivative works derived from tested 
classes and functions in their production; they are not affected by this 
license.
-->
<html><head>
<meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">
<title>JsUnit</title>
<link href="../../docs/JsUnit.css" rel="stylesheet" type="text/css">
</head><body>
<table width="100%" class="header"><tr>
<td width="100%"><div class="header"><span class="J">J</span><span class="s">s</span><span class="U">U</span>nit <small>1.2.beta.2</small></div></td>
<td>
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_xclick">
<input type="hidden" name="business" value="joehni@mail.berlios.de">
<input type="hidden" name="item_name" value="JsUnit">
<input type="image" src="../../docs/PayPal.png" border="0" name="submit" alt="Make a donation using PayPal">
</form></td>
<td><a href="http://developer.berlios.de/projects/jsunit"><img name="HeadBerliOS" src="../../docs/berlios.png" width="118" height="52" border="0" alt="Project Developer Home"></a></td>
<td><a href="http://www.doxygen.org/index.html"><img src="../../docs/doxygen.png" alt="doxygen" align="middle" border=0 width=110 height=52></a></td>
</tr></table>
<hr>
