#!/bin/sh

# JsUnit - a JUnit port for JavaScript
# Copyright (C) 1999,2000,2001,2002,2003 Joerg Schaible
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation in version 2 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# 
# Test suites built with JsUnit are derivative works derived from tested 
# classes and functions in their production; they are not affected by this 
# license.

if test -z $1 || test ! -d $1; then
	echo "Usage: genasp <targetroot>"
	exit 1
fi

genasp()
{
	mkdir -p $2/`dirname $1`
	echo -e "<%\n" > $2/`dirname $1`/`basename $1 .js`.inc
	cat $1 >> $2/`dirname $1`/`basename $1 .js`.inc
	echo -e "\n" >> $2/`dirname $1`/`basename $1 .js`.inc
	echo -n "%>" >> $2/`dirname $1`/`basename $1 .js`.inc
}

CWD=$PWD
JSUNIT_HOME=`dirname $0`/..

case $1 in
[a-zA-Z]:* | /*) TARGET=$1;;
*) TARGET=$PWD/$1;;
esac

cd $JSUNIT_HOME
for dir in lib samples tests; do
	rm -rf $TARGET/$dir
	for js in `find $dir -name "*.js" ! -path "*/CVS*" -prune`; do
		genasp $js $TARGET
	done
done

cd $CWD

unset CWD JSUNIT_HOME TARGET
