#!/bin/sh

# JsUnit - a JUnit port for JavaScript
# Copyright (C) 1999,2000,2001,2002 Joerg Schaible
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation in version 2 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# 
# Test suites built with JsUnit are derivative works derived from tested 
# classes and functions in their production; they are not affected by this 
# license.

type doxygen > /dev/null 2>&1
if test $? -ne 0; then
	if test -d /opt/doxygen/bin; then
		PATH=$PATH:/opt/doxygen/bin
	else
		echo "doxygen not available!"
		exit 1
	fi
fi
type dot > /dev/null 2>&1
if test $? -ne 0; then
	if test -d /opt/graphviz/bin; then
		HAVE_DOT="YES"
		PATH=$PATH:/opt/graphviz/bin
	elif test -d /opt/ATT/Graphviz/bin; then
		HAVE_DOT="YES"
		PATH=$PATH:/opt/ATT/Graphviz/bin
	else
		HAVE_DOT="NO"
	fi
else
	HAVE_DOT="YES"
fi
OUTPUT_DIRECTORY=.
VERSION=`dirname $0`/version.cfg
VERSION=`cat $VERSION`
GENERATE_HTML=YES
PERL_PATH=/usr/bin/perl
if test `uname -s | grep -ic CYGWIN` -gt 0; then
	PERL_PATH=`cygpath -aw $PERL_PATH`
fi
export GENERATE_HTML OUTPUT_DIRECTORY HAVE_DOT PERL_PATH VERSION
if test "$1" = "--keep-temp"; then
	KEEP=1
else
	KEEP=0
fi

CWD=$PWD
cd `dirname $0`/..
JSUNIT_HOME=$PWD
rm -rf .lib/ .docs/ docs/ > /dev/null 2>&1
mkdir .lib .docs 
PAGER=cat perldoc -t util/js2doxy.pl > .lib/js2doxy.man
cd $JSUNIT_HOME/lib
for js in *.js; do 
	../util/js2doxy.pl $js > ../.lib/$js
done

cd $JSUNIT_HOME
doxygen util/Doxyfile
cp util/*.png docs/
mv docs/*.html .docs/
cd $JSUNIT_HOME/.docs
for html in *.html; do 
	sed -e 's,<\([hH][1-9]\)>JsU\(nit.*\)</\1>,<\1><span class="J">J</span><span class="s">s</span><span class="U">U</span>\2</\1>,g' $html > ../docs/$html
#	if test "$html" = "index.html" -o -f ../util/`basename $html .html`.txt; then
#		mv ../docs/$html .$html
#		sed -e 's,<body>,<body><div class="JsUnit">,g' .$html | sed -e 's,</body>,</div></body>,g' > ../docs/$html
#	fi	
done

cd $JSUNIT_HOME/docs
chmod 644 *

cd $JSUNIT_HOME
if test $KEEP -eq 0; then 
	rm -rf .lib .docs
fi

#wget --mirror --convert-links --html-extension -nH --cut-dirs=2 -P docs http://localhost/JsUnit/php/index.php

cd $CWD

